"""The page header must stand on its own, not inside somebody's flex row.

A regression I introduced. `page_header` emits TWO block-level siblings — the
breadcrumb `<nav>` and its own `d-flex` title row. Dropping that into an
existing `<div class="d-flex justify-content-between">` turns both into flex
items, so the breadcrumb sits BESIDE the title instead of above it, with the
screen's buttons beside them again. The old hand-written `<h1>` was a single
element, which is why it worked in that container and the macro does not.

Two screens: purchase suggestions and the production plan.

The layout audit did not catch this — it checks alignment, overflow and target
sizes, not "is the breadcrumb above the title". Worth knowing: a clean audit is
evidence about the rules it encodes and nothing else.

Also pinned here: the "(tự động)" qualifier on the suggestions title. The old
heading read "Đề xuất mua hàng (tự động)"; replacing it with `t('Purchase
Suggestions')` dropped the only word telling the user the list is generated by
the system rather than written by a person.
"""
import io
import pathlib
import re

import pytest

TEMPLATES = pathlib.Path(__file__).resolve().parents[1] / 'app' / 'templates'

SCREENS = [
    'materials/purchase_suggestions.html',
    'production/plan.html',
]


@pytest.mark.parametrize('screen', SCREENS)
def test_the_header_is_not_inside_a_flex_row(screen):
    text = io.open(TEMPLATES / screen, encoding='utf-8').read()
    body = text.split('{% block content %}')[1]

    call = body.find('page_header(')
    assert call != -1, f'{screen} no longer calls page_header'

    before = body[:call]
    # Any d-flex container opened and not yet closed when the header is emitted.
    opened = len(re.findall(r'<div[^>]*\bd-flex\b', before))
    closed = len(re.findall(r'</div>', before))
    assert opened <= closed, (
        f'{screen} calls page_header inside an open d-flex row, so the '
        'breadcrumb renders beside the title instead of above it')


def test_the_suggestions_title_still_says_it_is_generated():
    """"(tự động)" was the only thing marking the list as machine-made."""
    text = io.open(TEMPLATES / 'materials' / 'purchase_suggestions.html',
                   encoding='utf-8').read()
    assert 'tự động' in text, (
        'the title no longer tells the user the list is generated'
    )


@pytest.mark.parametrize('screen', SCREENS)
def test_the_screen_keeps_its_secondary_buttons(screen):
    """Moving the header must not drop the toolbar that sat beside it."""
    text = io.open(TEMPLATES / screen, encoding='utf-8').read()
    assert 'btn-outline-secondary' in text, (
        f'{screen} lost its secondary action in the move')
