"""Document numbers generated by counting rows.

`_gen_po_number`, `_gen_gr_number` and the requisition equivalent all build the
next number as `count() + 1`. A count is not a sequence: delete any row and the
next number repeats one that has already been used.

Every one of these tables carries a unique constraint on (company, number), so
the repeat does not corrupt anything quietly — it raises an IntegrityError. But
for the person at the screen that is a crash with no explanation, on an action
that was going to work a minute earlier, and no amount of retrying fixes it
because the count does not change.

The fix takes the highest number already issued this month instead of counting
rows, so a deleted row leaves a gap rather than a collision. Gaps in document
numbering are normal and auditable; reuse is neither.
"""
import datetime as dt

import pytest

from app.services.procurement_service import ProcurementService
from app.services.requisition_service import RequisitionService


@pytest.fixture()
def supplier(app, seed):
    from app.config import db
    from app.models.models import Supplier

    with app.app_context():
        record = Supplier(company_id=seed['company_id'],
                          supplier_code='NCC-NUM', name='NCC Số')
        db.session.add(record)
        db.session.commit()
        return {'supplier_id': str(record.id), **seed}


def _make_po(app, company_id, store_id, supplier_id, number):
    from app.config import db
    from app.models.models import PurchaseOrder

    with app.app_context():
        order = PurchaseOrder(company_id=company_id, supplier_id=supplier_id,
                              store_id=store_id, po_number=number,
                              order_date=dt.date(2026, 6, 1),
                              status=PurchaseOrder.STATUS_DRAFT)
        db.session.add(order)
        db.session.commit()
        return str(order.id)


def test_a_number_is_never_reused_after_a_deletion(app, supplier):
    """Three orders, delete the middle one, and the next must not repeat it."""
    from app.config import db
    from app.models.models import PurchaseOrder

    with app.app_context():
        service = ProcurementService()
        issued = []
        for _ in range(3):
            number = service._gen_po_number(supplier['company_id'])
            _make_po(app, supplier['company_id'], supplier['store_id'],
                     supplier['supplier_id'], number)
            issued.append(number)

        assert len(set(issued)) == 3, 'the first three must already be distinct'

        middle = PurchaseOrder.query.filter_by(po_number=issued[1]).first()
        db.session.delete(middle)
        db.session.commit()

        next_number = service._gen_po_number(supplier['company_id'])
        assert next_number not in issued, (
            f'{next_number} was already used; counting rows reissues a number '
            f'as soon as one is deleted'
        )


def test_the_same_holds_for_goods_receipts(app, supplier):
    from app.config import db
    from app.models.models import GoodsReceipt

    with app.app_context():
        service = ProcurementService()
        issued = []
        for _ in range(3):
            number = service._gen_gr_number(supplier['company_id'])
            db.session.add(GoodsReceipt(
                company_id=supplier['company_id'],
                store_id=supplier['store_id'], gr_number=number,
                receipt_date=dt.date(2026, 6, 1)))
            db.session.commit()
            issued.append(number)

        db.session.delete(
            GoodsReceipt.query.filter_by(gr_number=issued[1]).first())
        db.session.commit()

        assert service._gen_gr_number(supplier['company_id']) not in issued


def test_the_same_holds_for_requisitions(app, supplier):
    from app.config import db
    from app.models.models import PurchaseRequisition

    with app.app_context():
        service = RequisitionService()
        issued = []
        for _ in range(3):
            number = service._gen_pr_number(supplier['company_id'])
            db.session.add(PurchaseRequisition(
                company_id=supplier['company_id'],
                store_id=supplier['store_id'], pr_number=number,
                request_date=dt.date(2026, 6, 1)))
            db.session.commit()
            issued.append(number)

        db.session.delete(
            PurchaseRequisition.query.filter_by(pr_number=issued[1]).first())
        db.session.commit()

        assert service._gen_pr_number(supplier['company_id']) not in issued


def test_numbers_are_still_sequential_with_nothing_deleted(app, supplier):
    """The ordinary case must keep producing 0001, 0002, 0003."""
    with app.app_context():
        service = ProcurementService()
        issued = []
        for _ in range(3):
            number = service._gen_po_number(supplier['company_id'])
            _make_po(app, supplier['company_id'], supplier['store_id'],
                     supplier['supplier_id'], number)
            issued.append(number)

        tails = [int(number.rsplit('-', 1)[1]) for number in issued]
        assert tails == [1, 2, 3]


def test_another_company_has_its_own_sequence(app, supplier):
    """Numbering is per company; a busy tenant must not skew a quiet one."""
    from app.config import db
    from app.models import Company, Store
    from app.models.models import Supplier

    with app.app_context():
        service = ProcurementService()
        number = service._gen_po_number(supplier['company_id'])
        _make_po(app, supplier['company_id'], supplier['store_id'],
                 supplier['supplier_id'], number)

        other = Company(company_code='NUM', name='Rival', email='r@num.test')
        db.session.add(other)
        db.session.flush()
        store = Store(company_id=other.id, store_code='NUS', name='S')
        rival_supplier = Supplier(company_id=other.id, supplier_code='NCC-R',
                                  name='NCC R')
        db.session.add_all([store, rival_supplier])
        db.session.commit()

        first_for_rival = service._gen_po_number(other.id)
        assert first_for_rival.endswith('0001')


# --- the two that carry no date in the series ----------------------------
#
# Supplier codes and production plan numbers run NCC-001 / KHSX-00001 with no
# month segment, but they are generated the same way and carry the same unique
# constraint, so they fail the same way.

def test_a_supplier_code_is_not_reused_after_a_deletion(app, seed):
    from app.config import db
    from app.models.models import Supplier
    from app.repositories.repository import SupplierRepository

    with app.app_context():
        repo = SupplierRepository()
        issued = []
        for _ in range(3):
            code = repo.get_next_code(seed['company_id'])
            db.session.add(Supplier(company_id=seed['company_id'],
                                    supplier_code=code, name=f'NCC {code}'))
            db.session.commit()
            issued.append(code)

        db.session.delete(
            Supplier.query.filter_by(supplier_code=issued[1]).first())
        db.session.commit()

        assert repo.get_next_code(seed['company_id']) not in issued


def test_a_plan_number_is_not_reused_after_a_deletion(app, seed):
    from app.config import db
    from app.models import Order
    from app.models.models import ProductionPlan
    from app.services.services import ProductionPlanService

    with app.app_context():
        # one plan per order, so each needs its own
        service = ProductionPlanService()
        issued = []
        for index in range(3):
            order = Order(company_id=seed['company_id'],
                          store_id=seed['store_id'],
                          customer_id=seed['customer_id'],
                          order_code=f'DH-KHSX-{index}', title='Sofa')
            db.session.add(order)
            db.session.flush()
            number = service._gen_plan_number(seed['company_id'])
            db.session.add(ProductionPlan(company_id=seed['company_id'],
                                          order_id=order.id,
                                          plan_number=number))
            db.session.commit()
            issued.append(number)

        db.session.delete(
            ProductionPlan.query.filter_by(plan_number=issued[1]).first())
        db.session.commit()

        assert service._gen_plan_number(seed['company_id']) not in issued

