"""production planning: plans, items, material lines, norms (F2)

Revision ID: 276bb213979a
Revises: 42d15126ff2c
Create Date: 2026-07-27 05:23:25.561111

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.models.types  # noqa: F401  (GUID and other custom column types)


# revision identifiers, used by Alembic.
revision: str = '276bb213979a'
down_revision: Union[str, Sequence[str], None] = '42d15126ff2c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('material_norms',
    sa.Column('id', app.models.types.GUID(), nullable=False),
    sa.Column('company_id', app.models.types.GUID(), nullable=False),
    sa.Column('product_key', sa.String(length=255), nullable=False),
    sa.Column('material_id', app.models.types.GUID(), nullable=False),
    sa.Column('quantity_per_unit', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('unit', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'product_key', 'material_id', name='uq_norm_company_product_material')
    )
    with op.batch_alter_table('material_norms', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_material_norms_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_material_norms_material_id'), ['material_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_material_norms_product_key'), ['product_key'], unique=False)

    op.create_table('production_plans',
    sa.Column('id', app.models.types.GUID(), nullable=False),
    sa.Column('company_id', app.models.types.GUID(), nullable=False),
    sa.Column('order_id', app.models.types.GUID(), nullable=False),
    sa.Column('contract_id', app.models.types.GUID(), nullable=True),
    sa.Column('plan_number', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'plan_number', name='uq_company_plan_number')
    )
    with op.batch_alter_table('production_plans', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_production_plans_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_production_plans_order_id'), ['order_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_production_plans_status'), ['status'], unique=False)

    op.create_table('production_plan_items',
    sa.Column('id', app.models.types.GUID(), nullable=False),
    sa.Column('plan_id', app.models.types.GUID(), nullable=False),
    sa.Column('source_name', sa.String(length=255), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('unit', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['plan_id'], ['production_plans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('production_plan_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_production_plan_items_plan_id'), ['plan_id'], unique=False)

    op.create_table('production_material_lines',
    sa.Column('id', app.models.types.GUID(), nullable=False),
    sa.Column('plan_id', app.models.types.GUID(), nullable=False),
    sa.Column('plan_item_id', app.models.types.GUID(), nullable=True),
    sa.Column('material_id', app.models.types.GUID(), nullable=False),
    sa.Column('quantity_required', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('quantity_issued', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('unit', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], ),
    sa.ForeignKeyConstraint(['plan_id'], ['production_plans.id'], ),
    sa.ForeignKeyConstraint(['plan_item_id'], ['production_plan_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('production_material_lines', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_production_material_lines_material_id'), ['material_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_production_material_lines_plan_id'), ['plan_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_production_material_lines_plan_item_id'), ['plan_item_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('production_material_lines', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_production_material_lines_plan_item_id'))
        batch_op.drop_index(batch_op.f('ix_production_material_lines_plan_id'))
        batch_op.drop_index(batch_op.f('ix_production_material_lines_material_id'))

    op.drop_table('production_material_lines')
    with op.batch_alter_table('production_plan_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_production_plan_items_plan_id'))

    op.drop_table('production_plan_items')
    with op.batch_alter_table('production_plans', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_production_plans_status'))
        batch_op.drop_index(batch_op.f('ix_production_plans_order_id'))
        batch_op.drop_index(batch_op.f('ix_production_plans_company_id'))

    op.drop_table('production_plans')
    with op.batch_alter_table('material_norms', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_material_norms_product_key'))
        batch_op.drop_index(batch_op.f('ix_material_norms_material_id'))
        batch_op.drop_index(batch_op.f('ix_material_norms_company_id'))

    op.drop_table('material_norms')
    # ### end Alembic commands ###
