"""baseline schema

Revision ID: 2ede8fb2868b
Revises: 
Create Date: 2026-07-26 00:09:07.500361

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.models.types  # noqa: F401  (GUID and other custom column types)


# revision identifiers, used by Alembic.
revision: str = '2ede8fb2868b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', app.models.types.GUID(), nullable=False),
    sa.Column('company_code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('production_address', sa.Text(), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('tax_code', sa.String(length=50), nullable=True),
    sa.Column('representative_name', sa.String(length=255), nullable=True),
    sa.Column('representative_title', sa.String(length=100), nullable=True),
    sa.Column('vat_rate', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('bank_accounts', sa.JSON(), nullable=True),
    sa.Column('timezone', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_companies_company_code'), ['company_code'], unique=True)
        batch_op.create_index(batch_op.f('ix_companies_is_active'), ['is_active'], unique=False)

    op.create_table('master_admins',
    sa.Column('id', app.models.types.GUID(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    with op.batch_alter_table('master_admins', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_master_admins_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_master_admins_username'), ['username'], unique=True)

    op.create_table('document_templates',
    sa.Column('id', app.models.types.GUID(), nullable=False),
    sa.Column('company_id', app.models.types.GUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('document_type', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('template_file', sa.String(length=255), nullable=False),
    sa.Column('template_content', sa.Text(), nullable=True),
    sa.Column('variables', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('document_templates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_document_templates_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_document_templates_is_active'), ['is_active'], unique=False)

    op.create_table('material_categories',
    sa.Column('id', app.models.types.GUID(), nullable=False),
    sa.Column('company_id', app.models.types.GUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'name', name='uq_company_category_name')
    )
    with op.batch_alter_table('material_categories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_material_categories_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_material_categories_is_active'), ['is_active'], unique=False)

    op.create_table('material_units',
    sa.Column('id', app.models.types.GUID(), nullable=False),
    sa.Column('company_id', app.models.types.GUID(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('abbreviation', sa.String(length=20), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'name', name='uq_company_unit_name')
    )
    with op.batch_alter_table('material_units', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_material_units_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_material_units_is_active'), ['is_active'], unique=False)

    op.create_table('stores',
    sa.Column('id', app.models.types.GUID(), nullable=False),
    sa.Column('company_id', app.models.types.GUID(), nullable=False),
    sa.Column('store_code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('manager_name', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'store_code', name='uq_company_store_code')
    )
    with op.batch_alter_table('stores', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stores_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_stores_is_active'), ['is_active'], unique=False)

    op.create_table('suppliers',
    sa.Column('id', app.models.types.GUID(), nullable=False),
    sa.Column('company_id', app.models.types.GUID(), nullable=False),
    sa.Column('supplier_code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('contact_person', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('tax_code', sa.String(length=50), nullable=True),
    sa.Column('payment_terms', sa.String(length=20), nullable=True),
    sa.Column('lead_time_days', sa.Integer(), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'supplier_code', name='uq_company_supplier_code')
    )
    with op.batch_alter_table('suppliers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_suppliers_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_suppliers_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_suppliers_name'), ['name'], unique=False)

    op.create_table('customers',
    sa.Column('id', app.models.types.GUID(), nullable=False),
    sa.Column('company_id', app.models.types.GUID(), nullable=False),
    sa.Column('store_id', app.models.types.GUID(), nullable=False),
    sa.Column('customer_code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('postal_code', sa.String(length=20), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('tax_code', sa.String(length=50), nullable=True),
    sa.Column('representative_name', sa.String(length=255), nullable=True),
    sa.Column('representative_title', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('store_id', 'customer_code', name='uq_store_customer_code')
    )
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_customers_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_customers_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_customers_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_customers_store_id'), ['store_id'], unique=False)

    op.create_table('materials',
    sa.Column('id', app.models.types.GUID(), nullable=False),
    sa.Column('company_id', app.models.types.GUID(), nullable=False),
    sa.Column('category_id', app.models.types.GUID(), nullable=True),
    sa.Column('unit_id', app.models.types.GUID(), nullable=True),
    sa.Column('supplier_id', app.models.types.GUID(), nullable=True),
    sa.Column('material_code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('color', sa.String(length=100), nullable=True),
    sa.Column('unit_price', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('supplier_sku', sa.String(length=100), nullable=True),
    sa.Column('min_stock_level', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('image_path', sa.String(length=500), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('spec_width_cm', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('spec_thickness_mm', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('spec_roll_length_m', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('spec_weight_per_unit', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('spec_weight_unit', sa.String(length=20), nullable=True),
    sa.Column('spec_composition', sa.String(length=255), nullable=True),
    sa.Column('spec_pattern', sa.String(length=50), nullable=True),
    sa.Column('spec_finish', sa.String(length=50), nullable=True),
    sa.Column('spec_durability_cycles', sa.Integer(), nullable=True),
    sa.Column('spec_density_kg_m3', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('spec_hardness', sa.String(length=50), nullable=True),
    sa.Column('spec_fire_resistance', sa.String(length=50), nullable=True),
    sa.Column('spec_water_resistance', sa.String(length=30), nullable=True),
    sa.Column('spec_uv_resistance', sa.String(length=30), nullable=True),
    sa.Column('spec_country_of_origin', sa.String(length=100), nullable=True),
    sa.Column('spec_certifications', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['material_categories.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.ForeignKeyConstraint(['unit_id'], ['material_units.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'material_code', name='uq_company_material_code')
    )
    with op.batch_alter_table('materials', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_materials_category_id'), ['category_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_materials_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_materials_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_materials_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_materials_supplier_id'), ['supplier_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_materials_unit_id'), ['unit_id'], unique=False)

    op.create_table('users',
    sa.Column('id', app.models.types.GUID(), nullable=False),
    sa.Column('company_id', app.models.types.GUID(), nullable=False),
    sa.Column('store_id', app.models.types.GUID(), nullable=True),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('position', sa.String(length=100), nullable=True),
    sa.Column('role', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'username', name='uq_company_username')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_store_id'), ['store_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=False)

    op.create_table('material_stock',
    sa.Column('id', app.models.types.GUID(), nullable=False),
    sa.Column('material_id', app.models.types.GUID(), nullable=False),
    sa.Column('company_id', app.models.types.GUID(), nullable=False),
    sa.Column('store_id', app.models.types.GUID(), nullable=True),
    sa.Column('current_quantity', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('material_id', 'store_id', name='uq_material_store_stock')
    )
    with op.batch_alter_table('material_stock', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_material_stock_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_material_stock_material_id'), ['material_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_material_stock_store_id'), ['store_id'], unique=False)

    op.create_table('orders',
    sa.Column('id', app.models.types.GUID(), nullable=False),
    sa.Column('company_id', app.models.types.GUID(), nullable=False),
    sa.Column('store_id', app.models.types.GUID(), nullable=False),
    sa.Column('customer_id', app.models.types.GUID(), nullable=False),
    sa.Column('order_code', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('total_amount', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('advance_amount', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('final_amount', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_canceled', sa.Boolean(), nullable=True),
    sa.Column('canceled_at', sa.DateTime(), nullable=True),
    sa.Column('canceled_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('store_id', 'order_code', name='uq_store_order_code')
    )
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_orders_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_orders_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_orders_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_orders_is_canceled'), ['is_canceled'], unique=False)
        batch_op.create_index(batch_op.f('ix_orders_store_id'), ['store_id'], unique=False)

    op.create_table('handover_records',
    sa.Column('id', app.models.types.GUID(), nullable=False),
    sa.Column('order_id', app.models.types.GUID(), nullable=False),
    sa.Column('report_number', sa.String(length=50), nullable=False),
    sa.Column('report_date', sa.Date(), nullable=False),
    sa.Column('handover_date', sa.Date(), nullable=False),
    sa.Column('handover_location', sa.Text(), nullable=True),
    sa.Column('start_time', sa.String(length=10), nullable=True),
    sa.Column('end_time', sa.String(length=10), nullable=True),
    sa.Column('copies_count', sa.Integer(), nullable=True),
    sa.Column('items', sa.JSON(), nullable=True),
    sa.Column('subtotal', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('vat_rate', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('vat_amount', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('shipping_fee', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('another_fee', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('total_amount', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('customer_representative', sa.String(length=200), nullable=True),
    sa.Column('customer_representative_title', sa.String(length=100), nullable=True),
    sa.Column('company_representative', sa.String(length=200), nullable=True),
    sa.Column('company_representative_title', sa.String(length=100), nullable=True),
    sa.Column('product_condition', sa.Text(), nullable=True),
    sa.Column('customer_signature_confirmed', sa.Boolean(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_confirmed', sa.Boolean(), nullable=True),
    sa.Column('confirmed_date', sa.DateTime(), nullable=True),
    sa.Column('is_canceled', sa.Boolean(), nullable=True),
    sa.Column('canceled_at', sa.DateTime(), nullable=True),
    sa.Column('canceled_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('report_number')
    )
    with op.batch_alter_table('handover_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_handover_records_is_canceled'), ['is_canceled'], unique=False)
        batch_op.create_index(batch_op.f('ix_handover_records_is_confirmed'), ['is_confirmed'], unique=False)
        batch_op.create_index(batch_op.f('ix_handover_records_order_id'), ['order_id'], unique=False)

    op.create_table('lifecycle_statuses',
    sa.Column('id', app.models.types.GUID(), nullable=False),
    sa.Column('order_id', app.models.types.GUID(), nullable=False),
    sa.Column('quotation_created', sa.Boolean(), nullable=True),
    sa.Column('quotation_created_at', sa.DateTime(), nullable=True),
    sa.Column('quotation_approved', sa.Boolean(), nullable=True),
    sa.Column('quotation_approved_at', sa.DateTime(), nullable=True),
    sa.Column('contract_created', sa.Boolean(), nullable=True),
    sa.Column('contract_created_at', sa.DateTime(), nullable=True),
    sa.Column('contract_signed', sa.Boolean(), nullable=True),
    sa.Column('contract_signed_at', sa.DateTime(), nullable=True),
    sa.Column('handover_confirmed', sa.Boolean(), nullable=True),
    sa.Column('handover_confirmed_at', sa.DateTime(), nullable=True),
    sa.Column('advance_paid', sa.Boolean(), nullable=True),
    sa.Column('advance_paid_at', sa.DateTime(), nullable=True),
    sa.Column('advance_skipped', sa.Boolean(), nullable=True),
    sa.Column('advance_skipped_at', sa.DateTime(), nullable=True),
    sa.Column('fully_paid', sa.Boolean(), nullable=True),
    sa.Column('fully_paid_at', sa.DateTime(), nullable=True),
    sa.Column('completed', sa.Boolean(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('lifecycle_statuses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lifecycle_statuses_order_id'), ['order_id'], unique=False)

    op.create_table('payment_reports',
    sa.Column('id', app.models.types.GUID(), nullable=False),
    sa.Column('order_id', app.models.types.GUID(), nullable=False),
    sa.Column('report_number', sa.String(length=50), nullable=False),
    sa.Column('payment_type', sa.String(length=50), nullable=False),
    sa.Column('report_date', sa.Date(), nullable=False),
    sa.Column('payment_date', sa.Date(), nullable=False),
    sa.Column('items', sa.JSON(), nullable=True),
    sa.Column('subtotal', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('vat_rate', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('vat_amount', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('shipping_fee', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('another_fee', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('advance_percentage', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('advance_amount', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('remaining_amount', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('amount_in_words', sa.String(length=500), nullable=True),
    sa.Column('work_completed_summary', sa.Text(), nullable=True),
    sa.Column('quotation_reference_date', sa.Date(), nullable=True),
    sa.Column('payment_method', sa.String(length=100), nullable=True),
    sa.Column('transaction_reference', sa.String(length=100), nullable=True),
    sa.Column('bank_account_info', sa.JSON(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_confirmed', sa.Boolean(), nullable=True),
    sa.Column('confirmed_date', sa.DateTime(), nullable=True),
    sa.Column('is_canceled', sa.Boolean(), nullable=True),
    sa.Column('canceled_at', sa.DateTime(), nullable=True),
    sa.Column('canceled_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('report_number')
    )
    with op.batch_alter_table('payment_reports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payment_reports_is_canceled'), ['is_canceled'], unique=False)
        batch_op.create_index(batch_op.f('ix_payment_reports_is_confirmed'), ['is_confirmed'], unique=False)
        batch_op.create_index(batch_op.f('ix_payment_reports_order_id'), ['order_id'], unique=False)

    op.create_table('quotations',
    sa.Column('id', app.models.types.GUID(), nullable=False),
    sa.Column('order_id', app.models.types.GUID(), nullable=False),
    sa.Column('quotation_number', sa.String(length=50), nullable=False),
    sa.Column('quotation_date', sa.Date(), nullable=False),
    sa.Column('validity_days', sa.Integer(), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('items', sa.JSON(), nullable=True),
    sa.Column('subtotal', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('vat_rate', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('vat_amount', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('shipping_fee', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('another_fee', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('total_amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('amount_in_words', sa.String(length=500), nullable=True),
    sa.Column('payment_terms', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_approved', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_canceled', sa.Boolean(), nullable=True),
    sa.Column('canceled_at', sa.DateTime(), nullable=True),
    sa.Column('canceled_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('quotation_number')
    )
    with op.batch_alter_table('quotations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_quotations_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_quotations_is_approved'), ['is_approved'], unique=False)
        batch_op.create_index(batch_op.f('ix_quotations_is_canceled'), ['is_canceled'], unique=False)
        batch_op.create_index(batch_op.f('ix_quotations_order_id'), ['order_id'], unique=False)

    op.create_table('contracts',
    sa.Column('id', app.models.types.GUID(), nullable=False),
    sa.Column('order_id', app.models.types.GUID(), nullable=False),
    sa.Column('quotation_id', app.models.types.GUID(), nullable=True),
    sa.Column('contract_number', sa.String(length=50), nullable=False),
    sa.Column('contract_date', sa.Date(), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('items', sa.JSON(), nullable=True),
    sa.Column('subtotal', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('vat_rate', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('vat_amount', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('shipping_fee', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('another_fee', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('contract_value', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('advance_percentage', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('advance_amount', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('amount_in_words', sa.Text(), nullable=True),
    sa.Column('contract_start_date', sa.Date(), nullable=True),
    sa.Column('contract_days_complete', sa.Integer(), nullable=True),
    sa.Column('selected_bank_index', sa.Integer(), nullable=True),
    sa.Column('num_date_notice_cancel', sa.Integer(), nullable=True),
    sa.Column('terms_and_conditions', sa.Text(), nullable=True),
    sa.Column('is_signed', sa.Boolean(), nullable=True),
    sa.Column('signed_date', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_canceled', sa.Boolean(), nullable=True),
    sa.Column('canceled_at', sa.DateTime(), nullable=True),
    sa.Column('canceled_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['quotation_id'], ['quotations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('contract_number')
    )
    with op.batch_alter_table('contracts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_contracts_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_contracts_is_canceled'), ['is_canceled'], unique=False)
        batch_op.create_index(batch_op.f('ix_contracts_is_signed'), ['is_signed'], unique=False)
        batch_op.create_index(batch_op.f('ix_contracts_order_id'), ['order_id'], unique=False)

    op.create_table('documents',
    sa.Column('id', app.models.types.GUID(), nullable=False),
    sa.Column('company_id', app.models.types.GUID(), nullable=False),
    sa.Column('order_id', app.models.types.GUID(), nullable=False),
    sa.Column('template_id', app.models.types.GUID(), nullable=True),
    sa.Column('quotation_id', app.models.types.GUID(), nullable=True),
    sa.Column('contract_id', app.models.types.GUID(), nullable=True),
    sa.Column('handover_record_id', app.models.types.GUID(), nullable=True),
    sa.Column('payment_report_id', app.models.types.GUID(), nullable=True),
    sa.Column('document_name', sa.String(length=255), nullable=False),
    sa.Column('document_type', sa.String(length=50), nullable=False),
    sa.Column('document_format', sa.String(length=10), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('variables_used', sa.JSON(), nullable=True),
    sa.Column('generated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ),
    sa.ForeignKeyConstraint(['handover_record_id'], ['handover_records.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['payment_report_id'], ['payment_reports.id'], ),
    sa.ForeignKeyConstraint(['quotation_id'], ['quotations.id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['document_templates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_documents_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_documents_order_id'), ['order_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_documents_order_id'))
        batch_op.drop_index(batch_op.f('ix_documents_company_id'))

    op.drop_table('documents')
    with op.batch_alter_table('contracts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_contracts_order_id'))
        batch_op.drop_index(batch_op.f('ix_contracts_is_signed'))
        batch_op.drop_index(batch_op.f('ix_contracts_is_canceled'))
        batch_op.drop_index(batch_op.f('ix_contracts_is_active'))

    op.drop_table('contracts')
    with op.batch_alter_table('quotations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_quotations_order_id'))
        batch_op.drop_index(batch_op.f('ix_quotations_is_canceled'))
        batch_op.drop_index(batch_op.f('ix_quotations_is_approved'))
        batch_op.drop_index(batch_op.f('ix_quotations_is_active'))

    op.drop_table('quotations')
    with op.batch_alter_table('payment_reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payment_reports_order_id'))
        batch_op.drop_index(batch_op.f('ix_payment_reports_is_confirmed'))
        batch_op.drop_index(batch_op.f('ix_payment_reports_is_canceled'))

    op.drop_table('payment_reports')
    with op.batch_alter_table('lifecycle_statuses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lifecycle_statuses_order_id'))

    op.drop_table('lifecycle_statuses')
    with op.batch_alter_table('handover_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_handover_records_order_id'))
        batch_op.drop_index(batch_op.f('ix_handover_records_is_confirmed'))
        batch_op.drop_index(batch_op.f('ix_handover_records_is_canceled'))

    op.drop_table('handover_records')
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_orders_store_id'))
        batch_op.drop_index(batch_op.f('ix_orders_is_canceled'))
        batch_op.drop_index(batch_op.f('ix_orders_is_active'))
        batch_op.drop_index(batch_op.f('ix_orders_customer_id'))
        batch_op.drop_index(batch_op.f('ix_orders_company_id'))

    op.drop_table('orders')
    with op.batch_alter_table('material_stock', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_material_stock_store_id'))
        batch_op.drop_index(batch_op.f('ix_material_stock_material_id'))
        batch_op.drop_index(batch_op.f('ix_material_stock_company_id'))

    op.drop_table('material_stock')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_store_id'))
        batch_op.drop_index(batch_op.f('ix_users_is_active'))
        batch_op.drop_index(batch_op.f('ix_users_email'))
        batch_op.drop_index(batch_op.f('ix_users_company_id'))

    op.drop_table('users')
    with op.batch_alter_table('materials', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_materials_unit_id'))
        batch_op.drop_index(batch_op.f('ix_materials_supplier_id'))
        batch_op.drop_index(batch_op.f('ix_materials_name'))
        batch_op.drop_index(batch_op.f('ix_materials_is_active'))
        batch_op.drop_index(batch_op.f('ix_materials_company_id'))
        batch_op.drop_index(batch_op.f('ix_materials_category_id'))

    op.drop_table('materials')
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_customers_store_id'))
        batch_op.drop_index(batch_op.f('ix_customers_name'))
        batch_op.drop_index(batch_op.f('ix_customers_is_active'))
        batch_op.drop_index(batch_op.f('ix_customers_company_id'))

    op.drop_table('customers')
    with op.batch_alter_table('suppliers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_suppliers_name'))
        batch_op.drop_index(batch_op.f('ix_suppliers_is_active'))
        batch_op.drop_index(batch_op.f('ix_suppliers_company_id'))

    op.drop_table('suppliers')
    with op.batch_alter_table('stores', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stores_is_active'))
        batch_op.drop_index(batch_op.f('ix_stores_company_id'))

    op.drop_table('stores')
    with op.batch_alter_table('material_units', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_material_units_is_active'))
        batch_op.drop_index(batch_op.f('ix_material_units_company_id'))

    op.drop_table('material_units')
    with op.batch_alter_table('material_categories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_material_categories_is_active'))
        batch_op.drop_index(batch_op.f('ix_material_categories_company_id'))

    op.drop_table('material_categories')
    with op.batch_alter_table('document_templates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_document_templates_is_active'))
        batch_op.drop_index(batch_op.f('ix_document_templates_company_id'))

    op.drop_table('document_templates')
    with op.batch_alter_table('master_admins', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_master_admins_username'))
        batch_op.drop_index(batch_op.f('ix_master_admins_is_active'))

    op.drop_table('master_admins')
    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_companies_is_active'))
        batch_op.drop_index(batch_op.f('ix_companies_company_code'))

    op.drop_table('companies')
    # ### end Alembic commands ###
