"""company reg-no/website/logo + contract warranty/delivery (template fields)

Revision ID: 5c706597ac41
Revises: 3b58dbc4e87a
Create Date: 2026-07-27 08:13:52.588725

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.models.types  # noqa: F401  (GUID and other custom column types)


# revision identifiers, used by Alembic.
revision: str = '5c706597ac41'
down_revision: Union[str, Sequence[str], None] = '3b58dbc4e87a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('business_registration_number', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('website', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('logo_path', sa.String(length=500), nullable=True))

    with op.batch_alter_table('contracts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('warranty_months', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('delivery_terms', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contracts', schema=None) as batch_op:
        batch_op.drop_column('delivery_terms')
        batch_op.drop_column('warranty_months')

    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.drop_column('logo_path')
        batch_op.drop_column('website')
        batch_op.drop_column('business_registration_number')

    # ### end Alembic commands ###
