"""purchase requisition (PR) + PO.pr_id

Revision ID: 61397f4c3104
Revises: a4733fe5b1e5
Create Date: 2026-07-30 18:14:11.072887

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.models.types  # noqa: F401  (GUID and other custom column types)


# revision identifiers, used by Alembic.
revision: str = '61397f4c3104'
down_revision: Union[str, Sequence[str], None] = 'a4733fe5b1e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('purchase_requisitions',
    sa.Column('id', app.models.types.GUID(), nullable=False),
    sa.Column('company_id', app.models.types.GUID(), nullable=False),
    sa.Column('store_id', app.models.types.GUID(), nullable=True),
    sa.Column('pr_number', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('request_date', sa.Date(), nullable=True),
    sa.Column('expected_date', sa.Date(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('extend01', sa.Text(), nullable=True),
    sa.Column('extend02', sa.Text(), nullable=True),
    sa.Column('extend03', sa.Text(), nullable=True),
    sa.Column('extend04', sa.Text(), nullable=True),
    sa.Column('extend05', sa.Text(), nullable=True),
    sa.Column('extend06', sa.Text(), nullable=True),
    sa.Column('extend07', sa.Text(), nullable=True),
    sa.Column('extend08', sa.Text(), nullable=True),
    sa.Column('extend09', sa.Text(), nullable=True),
    sa.Column('extend10', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'pr_number', name='uq_company_pr_number')
    )
    with op.batch_alter_table('purchase_requisitions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_purchase_requisitions_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_purchase_requisitions_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_purchase_requisitions_store_id'), ['store_id'], unique=False)

    op.create_table('purchase_requisition_lines',
    sa.Column('id', app.models.types.GUID(), nullable=False),
    sa.Column('pr_id', app.models.types.GUID(), nullable=False),
    sa.Column('material_id', app.models.types.GUID(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('unit', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], ),
    sa.ForeignKeyConstraint(['pr_id'], ['purchase_requisitions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('purchase_requisition_lines', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_purchase_requisition_lines_material_id'), ['material_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_purchase_requisition_lines_pr_id'), ['pr_id'], unique=False)

    with op.batch_alter_table('purchase_orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pr_id', app.models.types.GUID(), nullable=True))
        batch_op.create_index(batch_op.f('ix_purchase_orders_pr_id'), ['pr_id'], unique=False)
        batch_op.create_foreign_key('fk_purchase_orders_pr_id', 'purchase_requisitions', ['pr_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('purchase_orders', schema=None) as batch_op:
        batch_op.drop_constraint('fk_purchase_orders_pr_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_purchase_orders_pr_id'))
        batch_op.drop_column('pr_id')

    with op.batch_alter_table('purchase_requisition_lines', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_purchase_requisition_lines_pr_id'))
        batch_op.drop_index(batch_op.f('ix_purchase_requisition_lines_material_id'))

    op.drop_table('purchase_requisition_lines')
    with op.batch_alter_table('purchase_requisitions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_purchase_requisitions_store_id'))
        batch_op.drop_index(batch_op.f('ix_purchase_requisitions_status'))
        batch_op.drop_index(batch_op.f('ix_purchase_requisitions_company_id'))

    op.drop_table('purchase_requisitions')
    # ### end Alembic commands ###
