"""composite indexes on orders and customers (W8)

Revision ID: 68c0ef8699e4
Revises: e1b399a3d96d
Create Date: 2026-07-26 00:34:20.481563

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.models.types  # noqa: F401  (GUID and other custom column types)


# revision identifiers, used by Alembic.
revision: str = '68c0ef8699e4'
down_revision: Union[str, Sequence[str], None] = 'e1b399a3d96d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.create_index('ix_customers_company_active', ['company_id', 'is_active'], unique=False)
        batch_op.create_index('ix_customers_company_created', ['company_id', 'created_at'], unique=False)

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.create_index('ix_orders_company_active', ['company_id', 'is_active'], unique=False)
        batch_op.create_index('ix_orders_company_created', ['company_id', 'created_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_index('ix_orders_company_created')
        batch_op.drop_index('ix_orders_company_active')

    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.drop_index('ix_customers_company_created')
        batch_op.drop_index('ix_customers_company_active')

    # ### end Alembic commands ###
