"""user allowed_features (RBAC)

Revision ID: 9337d2190ede
Revises: 61397f4c3104
Create Date: 2026-08-12 21:27:00.199420

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.models.types  # noqa: F401  (GUID and other custom column types)


# revision identifiers, used by Alembic.
revision: str = '9337d2190ede'
down_revision: Union[str, Sequence[str], None] = '61397f4c3104'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('allowed_features', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('allowed_features')

    # ### end Alembic commands ###
