"""procurement (PO/GR) + extend fields on master data

Revision ID: a4733fe5b1e5
Revises: f7a1caafab25
Create Date: 2026-07-30 17:36:31.426530

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.models.types  # noqa: F401  (GUID and other custom column types)


# revision identifiers, used by Alembic.
revision: str = 'a4733fe5b1e5'
down_revision: Union[str, Sequence[str], None] = 'f7a1caafab25'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('purchase_orders',
    sa.Column('id', app.models.types.GUID(), nullable=False),
    sa.Column('company_id', app.models.types.GUID(), nullable=False),
    sa.Column('store_id', app.models.types.GUID(), nullable=True),
    sa.Column('supplier_id', app.models.types.GUID(), nullable=True),
    sa.Column('po_number', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('order_date', sa.Date(), nullable=True),
    sa.Column('expected_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('subtotal', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('vat_rate', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('vat_amount', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('total_amount', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('extend01', sa.Text(), nullable=True),
    sa.Column('extend02', sa.Text(), nullable=True),
    sa.Column('extend03', sa.Text(), nullable=True),
    sa.Column('extend04', sa.Text(), nullable=True),
    sa.Column('extend05', sa.Text(), nullable=True),
    sa.Column('extend06', sa.Text(), nullable=True),
    sa.Column('extend07', sa.Text(), nullable=True),
    sa.Column('extend08', sa.Text(), nullable=True),
    sa.Column('extend09', sa.Text(), nullable=True),
    sa.Column('extend10', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'po_number', name='uq_company_po_number')
    )
    with op.batch_alter_table('purchase_orders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_purchase_orders_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_purchase_orders_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_purchase_orders_store_id'), ['store_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_purchase_orders_supplier_id'), ['supplier_id'], unique=False)

    op.create_table('goods_receipts',
    sa.Column('id', app.models.types.GUID(), nullable=False),
    sa.Column('company_id', app.models.types.GUID(), nullable=False),
    sa.Column('po_id', app.models.types.GUID(), nullable=True),
    sa.Column('store_id', app.models.types.GUID(), nullable=True),
    sa.Column('gr_number', sa.String(length=50), nullable=False),
    sa.Column('receipt_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_posted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('extend01', sa.Text(), nullable=True),
    sa.Column('extend02', sa.Text(), nullable=True),
    sa.Column('extend03', sa.Text(), nullable=True),
    sa.Column('extend04', sa.Text(), nullable=True),
    sa.Column('extend05', sa.Text(), nullable=True),
    sa.Column('extend06', sa.Text(), nullable=True),
    sa.Column('extend07', sa.Text(), nullable=True),
    sa.Column('extend08', sa.Text(), nullable=True),
    sa.Column('extend09', sa.Text(), nullable=True),
    sa.Column('extend10', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['po_id'], ['purchase_orders.id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'gr_number', name='uq_company_gr_number')
    )
    with op.batch_alter_table('goods_receipts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_goods_receipts_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_goods_receipts_is_posted'), ['is_posted'], unique=False)
        batch_op.create_index(batch_op.f('ix_goods_receipts_po_id'), ['po_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_goods_receipts_store_id'), ['store_id'], unique=False)

    op.create_table('purchase_order_lines',
    sa.Column('id', app.models.types.GUID(), nullable=False),
    sa.Column('po_id', app.models.types.GUID(), nullable=False),
    sa.Column('material_id', app.models.types.GUID(), nullable=False),
    sa.Column('quantity_ordered', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('quantity_received', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('unit', sa.String(length=50), nullable=True),
    sa.Column('unit_price', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('line_total', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], ),
    sa.ForeignKeyConstraint(['po_id'], ['purchase_orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('purchase_order_lines', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_purchase_order_lines_material_id'), ['material_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_purchase_order_lines_po_id'), ['po_id'], unique=False)

    op.create_table('goods_receipt_lines',
    sa.Column('id', app.models.types.GUID(), nullable=False),
    sa.Column('gr_id', app.models.types.GUID(), nullable=False),
    sa.Column('po_line_id', app.models.types.GUID(), nullable=True),
    sa.Column('material_id', app.models.types.GUID(), nullable=False),
    sa.Column('quantity_received', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('unit', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['gr_id'], ['goods_receipts.id'], ),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], ),
    sa.ForeignKeyConstraint(['po_line_id'], ['purchase_order_lines.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('goods_receipt_lines', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_goods_receipt_lines_gr_id'), ['gr_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_goods_receipt_lines_material_id'), ['material_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_goods_receipt_lines_po_line_id'), ['po_line_id'], unique=False)

    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('extend01', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('extend02', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('extend03', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('extend04', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('extend05', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('extend06', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('extend07', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('extend08', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('extend09', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('extend10', sa.Text(), nullable=True))

    with op.batch_alter_table('materials', schema=None) as batch_op:
        batch_op.add_column(sa.Column('extend01', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('extend02', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('extend03', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('extend04', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('extend05', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('extend06', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('extend07', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('extend08', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('extend09', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('extend10', sa.Text(), nullable=True))

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('extend01', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('extend02', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('extend03', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('extend04', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('extend05', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('extend06', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('extend07', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('extend08', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('extend09', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('extend10', sa.Text(), nullable=True))

    with op.batch_alter_table('stores', schema=None) as batch_op:
        batch_op.add_column(sa.Column('extend01', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('extend02', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('extend03', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('extend04', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('extend05', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('extend06', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('extend07', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('extend08', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('extend09', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('extend10', sa.Text(), nullable=True))

    with op.batch_alter_table('suppliers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('extend01', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('extend02', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('extend03', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('extend04', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('extend05', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('extend06', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('extend07', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('extend08', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('extend09', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('extend10', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('suppliers', schema=None) as batch_op:
        batch_op.drop_column('extend10')
        batch_op.drop_column('extend09')
        batch_op.drop_column('extend08')
        batch_op.drop_column('extend07')
        batch_op.drop_column('extend06')
        batch_op.drop_column('extend05')
        batch_op.drop_column('extend04')
        batch_op.drop_column('extend03')
        batch_op.drop_column('extend02')
        batch_op.drop_column('extend01')

    with op.batch_alter_table('stores', schema=None) as batch_op:
        batch_op.drop_column('extend10')
        batch_op.drop_column('extend09')
        batch_op.drop_column('extend08')
        batch_op.drop_column('extend07')
        batch_op.drop_column('extend06')
        batch_op.drop_column('extend05')
        batch_op.drop_column('extend04')
        batch_op.drop_column('extend03')
        batch_op.drop_column('extend02')
        batch_op.drop_column('extend01')

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_column('extend10')
        batch_op.drop_column('extend09')
        batch_op.drop_column('extend08')
        batch_op.drop_column('extend07')
        batch_op.drop_column('extend06')
        batch_op.drop_column('extend05')
        batch_op.drop_column('extend04')
        batch_op.drop_column('extend03')
        batch_op.drop_column('extend02')
        batch_op.drop_column('extend01')

    with op.batch_alter_table('materials', schema=None) as batch_op:
        batch_op.drop_column('extend10')
        batch_op.drop_column('extend09')
        batch_op.drop_column('extend08')
        batch_op.drop_column('extend07')
        batch_op.drop_column('extend06')
        batch_op.drop_column('extend05')
        batch_op.drop_column('extend04')
        batch_op.drop_column('extend03')
        batch_op.drop_column('extend02')
        batch_op.drop_column('extend01')

    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.drop_column('extend10')
        batch_op.drop_column('extend09')
        batch_op.drop_column('extend08')
        batch_op.drop_column('extend07')
        batch_op.drop_column('extend06')
        batch_op.drop_column('extend05')
        batch_op.drop_column('extend04')
        batch_op.drop_column('extend03')
        batch_op.drop_column('extend02')
        batch_op.drop_column('extend01')

    with op.batch_alter_table('goods_receipt_lines', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_goods_receipt_lines_po_line_id'))
        batch_op.drop_index(batch_op.f('ix_goods_receipt_lines_material_id'))
        batch_op.drop_index(batch_op.f('ix_goods_receipt_lines_gr_id'))

    op.drop_table('goods_receipt_lines')
    with op.batch_alter_table('purchase_order_lines', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_purchase_order_lines_po_id'))
        batch_op.drop_index(batch_op.f('ix_purchase_order_lines_material_id'))

    op.drop_table('purchase_order_lines')
    with op.batch_alter_table('goods_receipts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_goods_receipts_store_id'))
        batch_op.drop_index(batch_op.f('ix_goods_receipts_po_id'))
        batch_op.drop_index(batch_op.f('ix_goods_receipts_is_posted'))
        batch_op.drop_index(batch_op.f('ix_goods_receipts_company_id'))

    op.drop_table('goods_receipts')
    with op.batch_alter_table('purchase_orders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_purchase_orders_supplier_id'))
        batch_op.drop_index(batch_op.f('ix_purchase_orders_store_id'))
        batch_op.drop_index(batch_op.f('ix_purchase_orders_status'))
        batch_op.drop_index(batch_op.f('ix_purchase_orders_company_id'))

    op.drop_table('purchase_orders')
    # ### end Alembic commands ###
