"""production plan lifecycle: is_delayed + delay_reason

Revision ID: f7a1caafab25
Revises: 5c706597ac41
Create Date: 2026-07-29 00:23:35.869216

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.models.types  # noqa: F401  (GUID and other custom column types)


# revision identifiers, used by Alembic.
revision: str = 'f7a1caafab25'
down_revision: Union[str, Sequence[str], None] = '5c706597ac41'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('production_plans', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_delayed', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('delay_reason', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('production_plans', schema=None) as batch_op:
        batch_op.drop_column('delay_reason')
        batch_op.drop_column('is_delayed')

    # ### end Alembic commands ###
